<?php

namespace App\Services;

final class MockAcademicService
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public function profiles(): array
    {
        return [
            'mahasiswa' => [
                'id' => 'mahasiswa',
                'name' => 'Realdho Fahryz',
                'roleLabel' => 'Mahasiswa',
                'departmentClass' => '3 D4 IT A',
                'idType' => 'NRP',
                'idNumber' => '1234567890',
                'email' => 'realdho@it.student.pens.ac.id',
                'avatarChar' => 'R',
                'classes' => [
                    [
                        'id' => 'm-wm',
                        'code' => 'WM',
                        'title' => 'Workshop Mesin Pembelajaran',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Senin',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 102',
                        'sks' => '3 SKS',
                        'hasShift' => true,
                        'shiftedSchedule' => 'Rabu, 13:00 - 16:00 di Lab C 103 (Jadwal Pengganti)',
                    ],
                    [
                        'id' => 'm-pmj',
                        'code' => 'PMJ',
                        'title' => 'Pemrograman Jaringan Lanjut',
                        'lecturer' => 'Nur Rosyid Mxxxx, S.Kom., M.T.',
                        'day' => 'Senin',
                        'time' => '13:00 - 16:00',
                        'startHour' => 13,
                        'durationHours' => 3,
                        'room' => 'Lab C 105',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-met',
                        'code' => 'MET',
                        'title' => 'Metodologi Penelitian Rekayasa',
                        'lecturer' => 'Achmad Basuki, Ph.D.',
                        'day' => 'Selasa',
                        'time' => '08:00 - 10:00',
                        'startHour' => 8,
                        'durationHours' => 2,
                        'room' => 'SAW-05.02',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-kw',
                        'code' => 'KW',
                        'title' => 'Kewirausahaan Teknologi',
                        'lecturer' => 'Rengga Axxxx, S.Kom., M.T.',
                        'day' => 'Selasa',
                        'time' => '11:00 - 13:00',
                        'startHour' => 11,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-k3l',
                        'code' => 'K3L',
                        'title' => 'Keamanan, Keselamatan & K3L',
                        'lecturer' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                        'day' => 'Rabu',
                        'time' => '15:00 - 17:00',
                        'startHour' => 15,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-pa1',
                        'code' => 'PA1',
                        'title' => 'Proyek Akhir Tahap 1',
                        'lecturer' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                        'day' => 'Kamis',
                        'time' => '09:00 - 12:00',
                        'startHour' => 9,
                        'durationHours' => 3,
                        'room' => 'Lab Software SAW-08',
                        'sks' => '4 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-pcd',
                        'code' => 'PCD',
                        'title' => 'Pengolahan Citra Digital',
                        'lecturer' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                        'day' => 'Kamis',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'D4-201',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-kp',
                        'code' => 'KP',
                        'title' => 'Kerja Praktek Industri',
                        'lecturer' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                        'day' => 'Jumat',
                        'time' => '08:00 - 10:00',
                        'startHour' => 8,
                        'durationHours' => 2,
                        'room' => 'Lab Sinyal B 204',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'm-bik',
                        'code' => 'BIK',
                        'title' => 'Bahasa Inggris Komunikasi Profesi',
                        'lecturer' => 'Tri Harsono, Ph.D.',
                        'day' => 'Jumat',
                        'time' => '10:00 - 12:00',
                        'startHour' => 10,
                        'durationHours' => 2,
                        'room' => 'B-101',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                ],
            ],
            'dosen' => [
                'id' => 'dosen',
                'name' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'roleLabel' => 'Dosen',
                'departmentClass' => 'Departemen Teknik Informatika',
                'idType' => 'NIP',
                'idNumber' => '197403252001121xxx',
                'email' => 'budi.sxxxx@pens.ac.id',
                'avatarChar' => 'B',
                'classes' => [
                    [
                        'id' => 'd-wma',
                        'code' => 'WM-A',
                        'title' => 'Workshop Mesin Pembelajaran (3 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Senin',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 102',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                        'hasPendingRequest' => true,
                        'pendingRequestDetail' => [
                            'id' => 'REQ-01',
                            'requester' => 'Realdho Fahryz (3 D4 IT A)',
                            'targetDay' => 'Rabu',
                            'targetTime' => '13:00 - 16:00',
                            'targetRoom' => 'Lab C 103',
                            'reason' => 'Tabrakan jadwal ujian sertifikasi internasional',
                        ],
                    ],
                    [
                        'id' => 'd-wmb',
                        'code' => 'WM-B',
                        'title' => 'Workshop Mesin Pembelajaran (3 D4 IT B)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Selasa',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 102',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'd-pba',
                        'code' => 'PBA',
                        'title' => 'Pengolahan Bahasa Alami (3 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Selasa',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'd-kcka',
                        'code' => 'KCK-A',
                        'title' => 'Kecerdasan Komputasional (4 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Rabu',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 104',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'd-kckb',
                        'code' => 'KCK-B',
                        'title' => 'Kecerdasan Komputasional (4 D4 IT B)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Kamis',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 104',
                        'sks' => '3 SKS',
                        'hasShift' => true,
                        'shiftedSchedule' => 'Jumat, 13:00 - 16:00 di Lab C 105 (Jadwal Pengganti)',
                    ],
                    [
                        'id' => 'd-pms',
                        'code' => 'PMS',
                        'title' => 'Pemodelan & Simulasi Sistem (2 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Kamis',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'SAW-05.02',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                        'hasPendingRequest' => true,
                        'pendingRequestDetail' => [
                            'id' => 'REQ-11',
                            'requester' => 'Gita Mxxxx (2 D4 IT A)',
                            'targetDay' => 'Selasa',
                            'targetTime' => '15:00 - 17:00',
                            'targetRoom' => 'SAW-05.02',
                            'reason' => 'Kegiatan perlombaan robotika nasional',
                        ],
                    ],
                    [
                        'id' => 'd-pm',
                        'code' => 'PM',
                        'title' => 'Pembelajaran Mendalam (Pascasarjana)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Jumat',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab Riset Lt 3',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                ],
            ],
            'baak' => [
                'id' => 'baak',
                'name' => 'Biro Administrasi Akademik',
                'roleLabel' => 'BAAK',
                'departmentClass' => 'Pusat Pelayanan & Penjadwalan',
                'idType' => 'Unit',
                'idNumber' => 'BAAK-PENS-01',
                'email' => 'baak@pens.ac.id',
                'avatarChar' => 'B',
                'stats' => [
                    'mahasiswa' => 1420,
                    'dosen' => 86,
                    'matakuliah' => 248,
                    'ruangan' => 42,
                ],
                'classes' => [
                    [
                        'id' => 'b-wm-a',
                        'code' => 'WM-A',
                        'title' => 'Workshop Mesin Pembelajaran (3 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Senin',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 102',
                        'sks' => '3 SKS',
                        'hasShift' => true,
                        'shiftedSchedule' => 'Rabu, 13:00 - 16:00 di Lab C 103',
                    ],
                    [
                        'id' => 'b-pmj-a',
                        'code' => 'PMJ-A',
                        'title' => 'Pemrograman Jaringan Lanjut (2 D4 IT A)',
                        'lecturer' => 'Nur Rosyid Mxxxx, S.Kom., M.T.',
                        'day' => 'Senin',
                        'time' => '13:00 - 16:00',
                        'startHour' => 13,
                        'durationHours' => 3,
                        'room' => 'Lab C 105',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-met-a',
                        'code' => 'MET-A',
                        'title' => 'Metodologi Penelitian Rekayasa (3 D4 IT A)',
                        'lecturer' => 'Achmad Basuki, Ph.D.',
                        'day' => 'Selasa',
                        'time' => '08:00 - 10:00',
                        'startHour' => 8,
                        'durationHours' => 2,
                        'room' => 'SAW-05.02',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-wm-b',
                        'code' => 'WM-B',
                        'title' => 'Workshop Mesin Pembelajaran (3 D4 IT B)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Selasa',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 102',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-kw-a',
                        'code' => 'KW-A',
                        'title' => 'Kewirausahaan Teknologi (3 D4 IT A)',
                        'lecturer' => 'Rengga Axxxx, S.Kom., M.T.',
                        'day' => 'Selasa',
                        'time' => '11:00 - 13:00',
                        'startHour' => 11,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-pba-a',
                        'code' => 'PBA-A',
                        'title' => 'Pengolahan Bahasa Alami (3 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Selasa',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-kck-a',
                        'code' => 'KCK-A',
                        'title' => 'Kecerdasan Komputasional (4 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Rabu',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 104',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-k3l-a',
                        'code' => 'K3L-A',
                        'title' => 'Keamanan, Keselamatan & K3L (1 D4 IT A)',
                        'lecturer' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                        'day' => 'Rabu',
                        'time' => '15:00 - 17:00',
                        'startHour' => 15,
                        'durationHours' => 2,
                        'room' => 'SAW-06.10',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-kck-b',
                        'code' => 'KCK-B',
                        'title' => 'Kecerdasan Komputasional (4 D4 IT B)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Kamis',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab C 104',
                        'sks' => '3 SKS',
                        'hasShift' => true,
                        'shiftedSchedule' => 'Jumat, 13:00 - 16:00 di Lab C 105',
                    ],
                    [
                        'id' => 'b-pa1-a',
                        'code' => 'PA1-A',
                        'title' => 'Proyek Akhir Tahap 1 (4 D4 IT A)',
                        'lecturer' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                        'day' => 'Kamis',
                        'time' => '09:00 - 12:00',
                        'startHour' => 9,
                        'durationHours' => 3,
                        'room' => 'Lab Software SAW-08',
                        'sks' => '4 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-pms-a',
                        'code' => 'PMS-A',
                        'title' => 'Pemodelan & Simulasi Sistem (2 D4 IT A)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Kamis',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'SAW-05.02',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-pcd-a',
                        'code' => 'PCD-A',
                        'title' => 'Pengolahan Citra Digital (3 D4 IT B)',
                        'lecturer' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                        'day' => 'Kamis',
                        'time' => '13:00 - 15:00',
                        'startHour' => 13,
                        'durationHours' => 2,
                        'room' => 'D4-201',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-kp-a',
                        'code' => 'KP-A',
                        'title' => 'Kerja Praktek Industri (3 D4 IT A)',
                        'lecturer' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                        'day' => 'Jumat',
                        'time' => '08:00 - 10:00',
                        'startHour' => 8,
                        'durationHours' => 2,
                        'room' => 'Lab Sinyal B 204',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-pm-a',
                        'code' => 'PM-A',
                        'title' => 'Pembelajaran Mendalam (Pascasarjana)',
                        'lecturer' => 'Dr. Ir. Budi Sxxxx, M.T.',
                        'day' => 'Jumat',
                        'time' => '08:00 - 11:00',
                        'startHour' => 8,
                        'durationHours' => 3,
                        'room' => 'Lab Riset Lt 3',
                        'sks' => '3 SKS',
                        'hasShift' => false,
                    ],
                    [
                        'id' => 'b-bik-a',
                        'code' => 'BIK-A',
                        'title' => 'Bahasa Inggris Komunikasi Profesi (2 D4 IT B)',
                        'lecturer' => 'Tri Harsono, Ph.D.',
                        'day' => 'Jumat',
                        'time' => '10:00 - 12:00',
                        'startHour' => 10,
                        'durationHours' => 2,
                        'room' => 'B-101',
                        'sks' => '2 SKS',
                        'hasShift' => false,
                    ],
                ],
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function rooms(): array
    {
        return [
            [
                'code' => 'C-102',
                'name' => 'Ruang Workshop Komputer C-102',
                'building' => 'Gedung D4',
            ],
            [
                'code' => 'C-103',
                'name' => 'Laboratorium Jaringan & IoT',
                'building' => 'Gedung D4',
            ],
            [
                'code' => 'C-104',
                'name' => 'Laboratorium Data Science & AI',
                'building' => 'Gedung D4',
            ],
            [
                'code' => 'C-105',
                'name' => 'Laboratorium Rekayasa Perangkat Lunak',
                'building' => 'Gedung D4',
            ],
            [
                'code' => 'SAW-06.10',
                'name' => 'Ruang Kuliah Teori Pascasarjana SAW-06.10',
                'building' => 'Gedung SAW',
            ],
            [
                'code' => 'SAW-08',
                'name' => 'Laboratorium Software Terpadu SAW-08',
                'building' => 'Gedung SAW',
            ],
            [
                'code' => 'SAW-05.02',
                'name' => 'Ruang Diskusi & Seminar SAW-05.02',
                'building' => 'Gedung SAW',
            ],
            [
                'code' => 'B-101',
                'name' => 'Ruang Laboratorium Bahasa B-101',
                'building' => 'Gedung D3',
            ],
            [
                'code' => 'B-204',
                'name' => 'Laboratorium Pemrosesan Sinyal B-204',
                'building' => 'Gedung D3',
            ],
            [
                'code' => 'D4-201',
                'name' => 'Ruang Teori Multimedia D4-201',
                'building' => 'Gedung D4',
            ],
            [
                'code' => 'Lab Riset Lt 3',
                'name' => 'Laboratorium Riset Terapan',
                'building' => 'Gedung Pasca',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function subjects(): array
    {
        return [
            [
                'code' => 'WMP301',
                'name' => 'Workshop Mesin Pembelajaran',
                'sks' => 3,
            ],
            [
                'code' => 'PMJ301',
                'name' => 'Pemrograman Jaringan Lanjut',
                'sks' => 3,
            ],
            [
                'code' => 'KCK301',
                'name' => 'Kecerdasan Komputasional',
                'sks' => 3,
            ],
            [
                'code' => 'PRO401',
                'name' => 'Proyek Akhir Tahap 1',
                'sks' => 4,
            ],
            [
                'code' => 'KPR201',
                'name' => 'Kerja Praktek Industri',
                'sks' => 2,
            ],
            [
                'code' => 'KWR201',
                'name' => 'Kewirausahaan Teknologi',
                'sks' => 2,
            ],
            [
                'code' => 'K3L201',
                'name' => 'Keamanan, Keselamatan & K3L',
                'sks' => 2,
            ],
            [
                'code' => 'PCD201',
                'name' => 'Pengolahan Citra Digital',
                'sks' => 2,
            ],
            [
                'code' => 'PBA201',
                'name' => 'Pengolahan Bahasa Alami',
                'sks' => 2,
            ],
            [
                'code' => 'MET201',
                'name' => 'Metodologi Penelitian Rekayasa',
                'sks' => 2,
            ],
            [
                'code' => 'PMS201',
                'name' => 'Pemodelan & Simulasi Sistem',
                'sks' => 2,
            ],
            [
                'code' => 'BIK201',
                'name' => 'Bahasa Inggris Komunikasi Profesi',
                'sks' => 2,
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function lecturers(): array
    {
        return [
            [
                'name' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'nip' => '197403252001121xxx',
            ],
            [
                'name' => 'Nur Rosyid Mxxxx, S.Kom., M.T.',
                'nip' => '198205142008121xxx',
            ],
            [
                'name' => 'Rengga Axxxx, S.Kom., M.T.',
                'nip' => '197908222005011xxx',
            ],
            [
                'name' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                'nip' => '198811052015042xxx',
            ],
            [
                'name' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                'nip' => '198501122010121xxx',
            ],
            [
                'name' => 'Achmad Basuki, Ph.D.',
                'nip' => '197006181995121xxx',
            ],
            [
                'name' => 'Tri Harsono, Ph.D.',
                'nip' => '197209241999031xxx',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function students(): array
    {
        return [
            [
                'name' => 'Realdho Fahryz',
                'nrp' => '1234567890',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Budi Santoso',
                'nrp' => '1234567001',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Siti Rahmawati',
                'nrp' => '1234567002',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Agus Prasetyo',
                'nrp' => '1234567003',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Dewi Lestari',
                'nrp' => '1234567004',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Eko Wibowo',
                'nrp' => '1234567005',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Fitri Handayani',
                'nrp' => '1234567006',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Gita Maharani',
                'nrp' => '1234567007',
                'cohort' => '2023',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Hendra Gunawan',
                'nrp' => '1234567008',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Indah Permata',
                'nrp' => '1234567009',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Joko Susilo',
                'nrp' => '1234567010',
                'cohort' => '2022',
                'major' => 'D4 Teknik Informatika',
            ],
            [
                'name' => 'Kartika Sari',
                'nrp' => '1234567011',
                'cohort' => '2023',
                'major' => 'D4 Teknik Informatika',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function rescheduleRequests(): array
    {
        return [
            [
                'id' => 'REQ-01',
                'courseId' => 'm-wm',
                'courseTitle' => 'Workshop Mesin Pembelajaran (3 D4 IT A)',
                'lecturerName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'requesterRole' => 'Mahasiswa',
                'requesterName' => 'Realdho Fahryz',
                'originalSchedule' => 'Senin, 08:00 - 11:00 (Lab C 102)',
                'proposedSchedule' => 'Rabu, 13:00 - 16:00 (Lab C 103)',
                'reason' => 'Tabrakan jadwal ujian sertifikasi internasional',
                'status' => 'Menunggu Persetujuan Dosen',
                'submittedAt' => '09 Okt 2026 08:30',
            ],
            [
                'id' => 'REQ-02',
                'courseId' => 'd-kckb',
                'courseTitle' => 'Kecerdasan Komputasional (4 D4 IT B)',
                'lecturerName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'originalSchedule' => 'Kamis, 08:00 - 11:00 (Lab C 104)',
                'proposedSchedule' => 'Jumat, 13:00 - 16:00 (Lab C 105)',
                'reason' => 'Penugasan dewan riset vokasi nasional',
                'status' => 'Disetujui',
                'submittedAt' => '08 Okt 2026 14:15',
            ],
            [
                'id' => 'REQ-03',
                'courseId' => 'b-pmj-a',
                'courseTitle' => 'Pemrograman Jaringan Lanjut (2 D4 IT A)',
                'lecturerName' => 'Nur Rosyid Mxxxx, S.Kom., M.T.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Nur Rosyid Mxxxx, S.Kom., M.T.',
                'originalSchedule' => 'Senin, 13:00 - 16:00 (Lab C 105)',
                'proposedSchedule' => 'Selasa, 08:00 - 11:00 (Lab C 105)',
                'reason' => 'Pemeliharaan berkala server workstation lab',
                'status' => 'Disetujui',
                'submittedAt' => '08 Okt 2026 11:20',
            ],
            [
                'id' => 'REQ-04',
                'courseId' => 'b-pcd-a',
                'courseTitle' => 'Pengolahan Citra Digital (3 D4 IT B)',
                'lecturerName' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                'requesterRole' => 'Mahasiswa',
                'requesterName' => 'Dimas Sxxxx',
                'originalSchedule' => 'Kamis, 13:00 - 15:00 (D4-201)',
                'proposedSchedule' => 'Jumat, 08:00 - 10:00 (D4-201)',
                'reason' => 'Kunjungan supervisi industri mahasiswa magang',
                'status' => 'Menunggu Persetujuan Dosen',
                'submittedAt' => '07 Okt 2026 16:40',
            ],
            [
                'id' => 'REQ-05',
                'courseId' => 'b-met-a',
                'courseTitle' => 'Metodologi Penelitian Rekayasa (3 D4 IT A)',
                'lecturerName' => 'Achmad Basuki, Ph.D.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Achmad Basuki, Ph.D.',
                'originalSchedule' => 'Selasa, 08:00 - 10:00 (SAW-05.02)',
                'proposedSchedule' => 'Kamis, 15:00 - 17:00 (SAW-05.02)',
                'reason' => 'Rapat koordinasi senat akademik politeknik',
                'status' => 'Disetujui',
                'submittedAt' => '07 Okt 2026 09:10',
            ],
            [
                'id' => 'REQ-06',
                'courseId' => 'b-kw-a',
                'courseTitle' => 'Kewirausahaan Teknologi (3 D4 IT A)',
                'lecturerName' => 'Rengga Axxxx, S.Kom., M.T.',
                'requesterRole' => 'Mahasiswa',
                'requesterName' => 'Siti Rahmawati',
                'originalSchedule' => 'Selasa, 11:00 - 13:00 (SAW-06.10)',
                'proposedSchedule' => 'Rabu, 09:00 - 11:00 (SAW-06.10)',
                'reason' => 'Jadwal kuliah tamu inkubator bisnis',
                'status' => 'Ditolak',
                'submittedAt' => '06 Okt 2026 15:00',
            ],
            [
                'id' => 'REQ-07',
                'courseId' => 'b-pa1-a',
                'courseTitle' => 'Proyek Akhir Tahap 1 (4 D4 IT A)',
                'lecturerName' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                'originalSchedule' => 'Kamis, 09:00 - 12:00 (SAW-08)',
                'proposedSchedule' => 'Senin, 09:00 - 12:00 (SAW-08)',
                'reason' => 'Penyamaan jadwal evaluasi berkala tahap 1',
                'status' => 'Disetujui',
                'submittedAt' => '06 Okt 2026 13:30',
            ],
            [
                'id' => 'REQ-08',
                'courseId' => 'b-bik-a',
                'courseTitle' => 'Bahasa Inggris Komunikasi Profesi (2 D4 IT B)',
                'lecturerName' => 'Tri Harsono, Ph.D.',
                'requesterRole' => 'Mahasiswa',
                'requesterName' => 'Fajar Wxxxx',
                'originalSchedule' => 'Jumat, 10:00 - 12:00 (B-101)',
                'proposedSchedule' => 'Kamis, 10:00 - 12:00 (B-101)',
                'reason' => 'Persiapan pameran pekan ilmiah mahasiswa',
                'status' => 'Menunggu Persetujuan Dosen',
                'submittedAt' => '05 Okt 2026 10:20',
            ],
            [
                'id' => 'REQ-09',
                'courseId' => 'b-pm-a',
                'courseTitle' => 'Pembelajaran Mendalam (Pascasarjana)',
                'lecturerName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'originalSchedule' => 'Jumat, 08:00 - 11:00 (Lab Riset Lt 3)',
                'proposedSchedule' => 'Sabtu, 08:00 - 11:00 (Lab Riset Lt 3)',
                'reason' => 'Akomodasi jadwal kelas karyawan terapan',
                'status' => 'Disetujui',
                'submittedAt' => '04 Okt 2026 17:00',
            ],
            [
                'id' => 'REQ-10',
                'courseId' => 'b-k3l-a',
                'courseTitle' => 'Keamanan, Keselamatan & K3L (1 D4 IT A)',
                'lecturerName' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Yanuar Risah Pxxxx, S.Kom., M.Kom.',
                'originalSchedule' => 'Rabu, 15:00 - 17:00 (SAW-06.10)',
                'proposedSchedule' => 'Senin, 15:00 - 17:00 (SAW-06.10)',
                'reason' => 'Simulasi tanggap darurat evakuasi gedung',
                'status' => 'Disetujui',
                'submittedAt' => '04 Okt 2026 14:10',
            ],
            [
                'id' => 'REQ-11',
                'courseId' => 'd-pms',
                'courseTitle' => 'Pemodelan & Simulasi Sistem (2 D4 IT A)',
                'lecturerName' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'requesterRole' => 'Mahasiswa',
                'requesterName' => 'Gita Maharani',
                'originalSchedule' => 'Kamis, 13:00 - 15:00 (SAW-05.02)',
                'proposedSchedule' => 'Selasa, 15:00 - 17:00 (SAW-05.02)',
                'reason' => 'Kegiatan perlombaan robotika nasional',
                'status' => 'Menunggu Persetujuan Dosen',
                'submittedAt' => '03 Okt 2026 11:45',
            ],
            [
                'id' => 'REQ-12',
                'courseId' => 'b-kp-a',
                'courseTitle' => 'Kerja Praktek Industri (3 D4 IT A)',
                'lecturerName' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                'requesterRole' => 'Dosen',
                'requesterName' => 'Renovita Exxxx, S.ST., M.Tr.Kom.',
                'originalSchedule' => 'Jumat, 08:00 - 10:00 (Lab Sinyal B 204)',
                'proposedSchedule' => 'Rabu, 10:00 - 12:00 (Lab Sinyal B 204)',
                'reason' => 'Supervisi langsung ke mitra industri politeknik',
                'status' => 'Disetujui',
                'submittedAt' => '02 Okt 2026 09:30',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function studentRoster(): array
    {
        return [
            [
                'no' => 1,
                'name' => 'Budi Santoso',
                'nrp' => '1234567xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 2,
                'name' => 'Siti Rahmawati',
                'nrp' => '1234568xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 3,
                'name' => 'Agus Prasetyo',
                'nrp' => '1234569xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 4,
                'name' => 'Dewi Lestari',
                'nrp' => '1234570xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 5,
                'name' => 'Eko Wibowo',
                'nrp' => '1234571xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 6,
                'name' => 'Fitri Handayani',
                'nrp' => '1234572xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 7,
                'name' => 'Hendra Gunawan',
                'nrp' => '1234573xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 8,
                'name' => 'Indah Permata',
                'nrp' => '1234574xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 9,
                'name' => 'Joko Susilo',
                'nrp' => '1234575xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 10,
                'name' => 'Kartika Sari',
                'nrp' => '1234576xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 11,
                'name' => 'Lukman Hakim',
                'nrp' => '1234577xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 12,
                'name' => 'Maya Anggraini',
                'nrp' => '1234578xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 13,
                'name' => 'Nur Hidayat',
                'nrp' => '1234579xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 14,
                'name' => 'Putri Ayu',
                'nrp' => '1234580xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 15,
                'name' => 'Realdho Fahryz',
                'nrp' => '1234567890',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 16,
                'name' => 'Rizky Pratama',
                'nrp' => '1234581xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 17,
                'name' => 'Sri Wahyuni',
                'nrp' => '1234582xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 18,
                'name' => 'Tri Nugroho',
                'nrp' => '1234583xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 19,
                'name' => 'Wahyu Setiawan',
                'nrp' => '1234584xxx',
                'class' => '3 D4 IT A',
            ],
            [
                'no' => 20,
                'name' => 'Yulia Citra',
                'nrp' => '1234585xxx',
                'class' => '3 D4 IT A',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function systemLogs(): array
    {
        return [
            [
                'id' => 'LOG-1001',
                'timestamp' => '10 Okt 2026 08:42',
                'level' => 'shift',
                'levelLabel' => 'Perubahan Jadwal',
                'actor' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'module' => 'Scheduler Engine',
                'detail' => 'Jadwal Workshop Mesin Pembelajaran dipindahkan ke Rabu, 13:00 - 16:00 (Lab C 103) secara otomatis.',
                'status' => 'Sukses',
            ],
            [
                'id' => 'LOG-1002',
                'timestamp' => '10 Okt 2026 08:30',
                'level' => 'info',
                'levelLabel' => 'Info',
                'actor' => 'Realdho Fahryz (1234567890)',
                'module' => 'Pengajuan Mahasiswa',
                'detail' => 'Pengajuan baru permohonan perpindahan jadwal untuk Workshop Mesin Pembelajaran diajukan.',
                'status' => 'Terkirim',
            ],
            [
                'id' => 'LOG-1003',
                'timestamp' => '10 Okt 2026 07:15',
                'level' => 'sync',
                'levelLabel' => 'Sinkronisasi CSV',
                'actor' => 'BAAK Admin (Biro Akademik)',
                'module' => 'Data Ingestion',
                'detail' => 'Sinkronisasi berkas jadwal_semester_ganjil_2026.csv berhasil memvalidasi 48 baris perkuliahan.',
                'status' => 'Selesai',
            ],
            [
                'id' => 'LOG-1004',
                'timestamp' => '10 Okt 2026 06:00',
                'level' => 'info',
                'levelLabel' => 'Info',
                'actor' => 'Sistem Otomatis',
                'module' => 'Integritas Jadwal',
                'detail' => 'Pemeriksaan integritas matriks mingguan 7 hari selesai: 0 konflik jadwal terdeteksi pada 42 ruangan.',
                'status' => 'Optimal',
            ],
            [
                'id' => 'LOG-1005',
                'timestamp' => '09 Okt 2026 16:45',
                'level' => 'warning',
                'levelLabel' => 'Peringatan',
                'actor' => 'Petugas Sarpras',
                'module' => 'Manajemen Fasilitas',
                'detail' => 'Pemeliharaan berkala AC di Ruang Workshop Komputer C-102 dijadwalkan akhir pekan.',
                'status' => 'Perhatian',
            ],
            [
                'id' => 'LOG-1006',
                'timestamp' => '09 Okt 2026 14:15',
                'level' => 'shift',
                'levelLabel' => 'Perubahan Jadwal',
                'actor' => 'Dr. Ir. Budi Sxxxx, M.T.',
                'module' => 'Persetujuan Dosen',
                'detail' => 'Permohonan perpindahan jadwal Kecerdasan Komputasional (4 D4 IT B) disetujui Dosen.',
                'status' => 'Disetujui',
            ],
            [
                'id' => 'LOG-1007',
                'timestamp' => '09 Okt 2026 11:20',
                'level' => 'error',
                'levelLabel' => 'Error',
                'actor' => 'Parser CSV',
                'module' => 'Validasi Kurikulum',
                'detail' => 'Ditemukan kode matakuliah tidak valid (XYZ999) pada baris ke-3 berkas CSV impor. Baris ditolak.',
                'status' => 'Dicegah',
            ],
            [
                'id' => 'LOG-1008',
                'timestamp' => '09 Okt 2026 09:00',
                'level' => 'info',
                'levelLabel' => 'Info',
                'actor' => 'BAAK Admin',
                'module' => 'Autentikasi',
                'detail' => 'Sesi login admin BAAK berhasil dari alamat jaringan internal (10.12.0.14).',
                'status' => 'Sukses',
            ],
            [
                'id' => 'LOG-1009',
                'timestamp' => '08 Okt 2026 17:30',
                'level' => 'sync',
                'levelLabel' => 'Backup Sistem',
                'actor' => 'Database Service',
                'module' => 'Pencadangan',
                'detail' => 'Snapshot harian PostgreSQL berhasil dibuat dan diarsipkan (Ukuran: 42.8 MB).',
                'status' => 'Sukses',
            ],
            [
                'id' => 'LOG-1010',
                'timestamp' => '08 Okt 2026 13:10',
                'level' => 'warning',
                'levelLabel' => 'Peringatan',
                'actor' => 'Scheduler Engine',
                'module' => 'Deteksi Kapasitas',
                'detail' => 'Ruang Kuliah Teori SAW-06.10 terisi 38 dari 40 kapasitas maksimum pada sesi perkuliahan siang.',
                'status' => 'Mendekati Batas',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function recommendationSlots(): array
    {
        return [
            [
                'day' => 'Rabu',
                'time' => '13:00 - 16:00',
                'room' => 'Lab C 103',
                'note' => 'Bebas Sesi Praktikum Lain',
            ],
            [
                'day' => 'Kamis',
                'time' => '13:00 - 15:00',
                'room' => 'SAW-06.10',
                'note' => 'Kapasitas 40 Kursi Mahasiswa',
            ],
            [
                'day' => 'Jumat',
                'time' => '08:00 - 11:00',
                'room' => 'Lab C 102',
                'note' => 'Slot Pagi Kosong & Workstation Siap',
            ],
            [
                'day' => 'Selasa',
                'time' => '15:00 - 17:00',
                'room' => 'Lab Software SAW-08',
                'note' => 'Bebas Bentrok Dosen',
            ],
            [
                'day' => 'Senin',
                'time' => '13:00 - 15:00',
                'room' => 'Lab Sinyal B 204',
                'note' => 'Laboratorium Tersedia Penuh',
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function payload(): array
    {
        return [
            'appData' => $this->profiles(),
            'masterRooms' => $this->rooms(),
            'masterSubjects' => $this->subjects(),
            'masterLecturers' => $this->lecturers(),
            'masterStudents' => $this->students(),
            'rescheduleRequests' => $this->rescheduleRequests(),
            'studentRoster' => $this->studentRoster(),
            'systemLogs' => $this->systemLogs(),
            'recommendationSlots' => $this->recommendationSlots(),
        ];
    }
}
